### CREATE NEW USERS
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "session@solomon.id",
  "password": "sessionsession"
}

### LOGIN USERS
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "novin@solomon.id",
  "password": "novinnovin"
}

### WHOAMI
GET http://localhost:3000/auth/whoami

### LOGOUT
POST http://localhost:3000/auth/signout

### SET COLOR WITH PARAM
GET http://localhost:3000/auth/colors/blue

### GET COLORS
GET http://localhost:3000/auth/colors

### FIND USER BY ID
GET http://localhost:3000/auth/1

### FIND ALL USERS BY EMAIL
GET http://localhost:3000/auth?email=doni@solomon.id

### REMOVE USERS BY ID
DELETE http://localhost:3000/auth/2

### UPDATE USERS BY ID
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
  "email": "novin@solomon.id"
}
